# Generated by Django 4.2.1 on 2025-04-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('race', models.CharField(max_length=100)),
                ('specie', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('born_on', models.DateField()),
                ('energy', models.FloatField(default=100)),
                ('moral', models.FloatField(default=100)),
                ('health', models.FloatField(default=100)),
                ('res', models.FloatField(default=0)),
                ('vit', models.FloatField(default=0)),
                ('dre', models.FloatField(default=0)),
                ('gal', models.FloatField(default=0)),
                ('sar', models.FloatField(default=0)),
                ('tra', models.FloatField(default=0)),
                ('ac_res', models.FloatField(default=0)),
                ('ac_vit', models.FloatField(default=0)),
                ('ac_dre', models.FloatField(default=0)),
                ('ac_gal', models.FloatField(default=0)),
                ('ac_sar', models.FloatField(default=0)),
                ('ac_tra', models.FloatField(default=0)),
                ('GP', models.FloatField(default=0)),
                ('BLUP', models.FloatField(default=0)),
                ('mother', models.CharField(blank=True, max_length=100, null=True)),
                ('father', models.CharField(blank=True, max_length=100, null=True)),
                ('breed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep', models.BooleanField(default=False)),
            ],
        ),
    ]
