# Generated by Django 4.2.1 on 2025-04-18 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mail', models.EmailField(default='', max_length=254, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('pwd', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_res', models.FloatField(default=0)),
                ('base_vit', models.FloatField(default=0)),
                ('base_dre', models.FloatField(default=0)),
                ('base_gal', models.FloatField(default=0)),
                ('base_sar', models.FloatField(default=0)),
                ('base_tra', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('specie', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('born_on', models.DateField()),
                ('energy', models.FloatField(default=100)),
                ('moral', models.FloatField(default=100)),
                ('health', models.FloatField(default=100)),
                ('res', models.FloatField()),
                ('vit', models.FloatField()),
                ('dre', models.FloatField()),
                ('gal', models.FloatField()),
                ('sar', models.FloatField()),
                ('tra', models.FloatField()),
                ('ac_res', models.FloatField(default=0)),
                ('ac_vit', models.FloatField(default=0)),
                ('ac_dre', models.FloatField(default=0)),
                ('ac_gal', models.FloatField(default=0)),
                ('ac_sar', models.FloatField(default=0)),
                ('ac_tra', models.FloatField(default=0)),
                ('GP', models.FloatField(default=0)),
                ('BLUP', models.FloatField(default=0)),
                ('mother', models.CharField(blank=True, max_length=100, null=True)),
                ('father', models.CharField(blank=True, max_length=100, null=True)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dragons', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dragons', to='dragons.race')),
            ],
            options={
                'db_table': 'dragons',
            },
        ),
    ]
