# Generated by Django 4.2.1 on 2025-04-17 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('pwd', models.CharField(max_length=255, null=True)),
                ('mail', models.CharField(max_length=255, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('ipaddr', models.CharField(max_length=255, null=True)),
                ('allowed', models.CharField(max_length=255, null=True)),
                ('giftbox', models.CharField(max_length=255, null=True)),
                ('inventory_id', models.IntegerField(null=True)),
                ('a_rank', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('race', models.CharField(max_length=100)),
                ('specie', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('born_on', models.DateField()),
                ('energy', models.FloatField(default=100)),
                ('moral', models.FloatField(default=100)),
                ('health', models.FloatField(default=100)),
                ('res', models.FloatField(default=0)),
                ('vit', models.FloatField(default=0)),
                ('dre', models.FloatField(default=0)),
                ('gal', models.FloatField(default=0)),
                ('sar', models.FloatField(default=0)),
                ('tra', models.FloatField(default=0)),
                ('ac_res', models.FloatField(default=0)),
                ('ac_vit', models.FloatField(default=0)),
                ('ac_dre', models.FloatField(default=0)),
                ('ac_gal', models.FloatField(default=0)),
                ('ac_sar', models.FloatField(default=0)),
                ('ac_tra', models.FloatField(default=0)),
                ('GP', models.FloatField(default=0)),
                ('BLUP', models.FloatField(default=0)),
                ('mother', models.CharField(blank=True, max_length=100, null=True)),
                ('father', models.CharField(blank=True, max_length=100, null=True)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dragons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dragons',
            },
        ),
    ]
