# Generated by Django 4.2.1 on 2025-04-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a representative image for this race', null=True, upload_to='race_images/'),
        ),
    ]
