# Generated by Django 4.2.1 on 2025-04-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragons', '0002_remove_player_a_rank_remove_player_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pwd',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
