# Generated by Django 4.2.1 on 2025-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragons', '0003_remove_race_image_race_image_female_race_image_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='diamonds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='silver',
            field=models.IntegerField(default=0),
        ),
    ]
