# Generated by Django 4.2.1 on 2025-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragons', '0004_player_diamonds_player_gold_player_silver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='diamonds',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='gold',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='silver',
            field=models.IntegerField(default=5000),
        ),
    ]
